### ISSUE TITLE
Create and upload pip package for tf big

### ISSUE THREAD

**Issue by justin1121** [tf-encrypted/tf-big#18]

**Comment by justin1121** [comment]
Ability to build pip packages here https://github.com/tf-encrypted/tf-big/pull/19, just need to build them and upload them.

**Comment by mortendahl** [comment]
Just pushed a first package; you should be able to log in with usual credentials!

**Comment by justin1121** [comment]
I've uploaded pip packages for MacOS python 3.5, 3.6 and 3.7 and Linux 3.5 and 3.6. 3.7 should hopefully come soon, see https://github.com/tf-encrypted/tf-big/issues/22.
