### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by justin1121** [tf-encrypted/tf-big#2]
I think we probably want to implement our continuous integration on travis ci so we get windows build support out of the box.

**Comment by justin1121** [comment]
@mortendahl what do you think about this?

**Comment by mortendahl** [comment]
Yeah I like that, we can use it to test TFE for Windows as well. It should be active for TF Big now (using Travis CI for Open Source at https://travis-ci.org/tf-encrypted/tf-big)

**Comment by justin1121** [comment]
We've had some trouble with travis ci supporting python on macos builds and circleci is launching windows support soon (early access is currently available) so we'll just stick to circleci. If we want to test window builds before that we can do something with travis or https://www.appveyor.com/.
