### ISSUE TITLE
Automate pip package distribution

### ISSUE THREAD

**Issue by justin1121** [tf-encrypted/tf-big#20]
In the future, we may want to make distributing pip packages for TF Big easier. We can make an automatic deploy using circleci.

**Comment by justin1121** [comment]
With the latest PR https://github.com/tf-encrypted/tf-big/pull/19 it was discovered that we'll want to upload a different pip package for every python version we'll want to support. I think we'll want to figure out how to do this for TFE first (https://github.com/tf-encrypted/tf-encrypted/issues/595 and #283) and then pull the changes into this repository.

**Comment by mortendahl** [comment]
Some steps already taken in https://github.com/tf-encrypted/tf-big/pull/47 and https://github.com/tf-encrypted/tf-big/pull/48

**Comment by mortendahl** [comment]
This is finished with https://github.com/tf-encrypted/tf-big/commit/4bcd9f1b7619f6f058c4c15acb16d76d59dba762
