### ISSUE TITLE
What to do

### ISSUE THREAD

**Issue by mortendahl** [tf-encrypted/tf-big#21]
```python
import tf_big as tfb
x = tfb.big_import([[123]])
y = x+x
```

the above currently fails due to TF type checks:

```
TypeError: Value passed to parameter 'x' has DataType variant not in list of allowed values: bfloat16, float16, float32, float64, uint8, int8, int16, int32, int64, complex64, complex128, string
```

We should decide what to do

**Comment by justin1121** [comment]
Even if this didn't get caught by the type check it wouldn't know what function to call to add two variants together.

**Comment by mortendahl** [comment]
Have you seen a way to register a kernel for `(variant, 'BigTensor')` instead of just `variant`?

Alternatively we could wrap the variant tensor in python land and overload operations there. We'd have to find a way to minimise manually wrapping and unwrapping.

**Comment by justin1121** [comment]
Nope don't think that's possible. I don't think there's anyway around implementing the convenience functions, such as this, in python ourselves.

**Comment by mortendahl** [comment]
What do you think about adding a Python wrapper then?

**Comment by justin1121** [comment]
Makes sense to me. Have an issue here https://github.com/tf-encrypted/tf-big/issues/3. Don't think its a high priority though.

**Comment by mortendahl** [comment]
We followed the Python wrapper approach (#3)
