### ISSUE TITLE
Compile SO file using `tf_custom_op_library` rule?

### ISSUE THREAD

**Issue by mortendahl** [tf-encrypted/tf-big#26]
From [official doc](https://www.tensorflow.org/guide/extend/op#compile_the_op_using_bazel_tensorflow_source_installation):

> Note: Although you can create a shared library (a .so file) with the standard cc_library rule, we strongly recommend that you use the tf_custom_op_library macro. It adds some required dependencies, and performs checks to ensure that the shared library is compatible with TensorFlow's plugin loading mechanism.

**Comment by justin1121** [comment]
Problem with this is that the `tf_custom_op_library` is not easily exposed. We'd have to download all of the tensorflow source or copy and paste this function from tensorflow. This is probably why they're not doing it in https://github.com/tensorflow/custom-op. I'd argue if they're not recommending using it in that example repo than its not really needed.

**Comment by mortendahl** [comment]
Closing following @justin1121's remark
