### ISSUE TITLE
Segfault when limb_format=True

### ISSUE THREAD

**Issue by jvmncs** [tf-encrypted/tf-big#71]
Script for reproducing:
```python
import tensorflow as tf
import tf_big

mod_bits = 32

p, q, n = tf_big.random_rsa_modulus(mod_bits)
pb = tf_big.convert_from_tensor(p, tf.string)
qb = tf_big.convert_from_tensor(q, tf.string)
nb = tf_big.convert_from_tensor(n, tf.string)
print(pb, qb, nb)  # all good
byt = tf_big.convert_from_tensor(n, tf.int32, True, mod_bits)  # Segfault
print(byt)
```

**Comment by rdragos** [comment]
Hmmm, interesting. Will look into it tomorrow - any chance that works if you increase `mod_bits` in the last call?

**Comment by rdragos** [comment]
Seems like the issue is that the TensorShape of `n` is an empty list. I think that's where the problem is since `export_limbs` op expects a 2D array.

**Comment by jvmncs** [comment]
>any chance that works if you increase mod_bits in the last call?

nope, tried a ton of combinations there, but I think you may have figured it out
